import { Text, type WeatherForecast } from "@/api/types/WeatherForecast";

export const sampleWeatherPayload: WeatherForecast = {
  location: {
    name: 'Nashville',
    region: 'Tennessee',
    country: 'United States of America',
    lat: 36.17,
    lon: -86.78,
    tz_id: 'America/Chicago',
    localtime_epoch: 1697573376,
    localtime: '2023-10-17 15:09'
  },
  current: {
    last_updated_epoch: 1697572800,
    last_updated: '2023-10-17 15:00',
    temp_c: 14.4,
    temp_f: 57.9,
    is_day: 1,
    condition: {
      text: Text.Overcast,
      icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
      code: 1009
    },
    wind_mph: 6.9,
    wind_kph: 11.2,
    wind_degree: 270,
    wind_dir: 'W',
    pressure_mb: 1020.0,
    pressure_in: 30.13,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 57,
    cloud: 100,
    feelslike_c: 14.7,
    feelslike_f: 58.5,
    vis_km: 16.0,
    vis_miles: 9.0,
    uv: 4.0,
    gust_mph: 3.6,
    gust_kph: 5.8
  },
  forecast: {
    forecastday: [
      {
        date: '2023-10-17',
        date_epoch: 1697500800,
        day: {
          maxtemp_c: 18.2,
          maxtemp_f: 64.8,
          mintemp_c: 11.1,
          mintemp_f: 52.0,
          avgtemp_c: 14.6,
          avgtemp_f: 58.2,
          maxwind_mph: 3.6,
          maxwind_kph: 5.8,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 70.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: Text.Overcast,
            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
            code: 1003
          },
          uv: 4.0
        },
        astro: {
          sunrise: '06:56 AM',
          sunset: '06:09 PM',
          moonrise: '09:53 AM',
          moonset: '07:46 PM',
          moon_phase: 'Waxing Crescent',
          moon_illumination: '5',
          is_moon_up: 1,
          is_sun_up: 0
        },
        hour: [
          {
            time_epoch: 1697518800,
            time: '2023-10-17 00:00',
            temp_c: 12.6,
            temp_f: 54.7,
            is_day: 0,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 351,
            wind_dir: 'N',
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 38,
            feelslike_c: 12.1,
            feelslike_f: 53.7,
            windchill_c: 12.1,
            windchill_f: 53.7,
            heatindex_c: 12.6,
            heatindex_f: 54.7,
            dewpoint_c: 7.4,
            dewpoint_f: 45.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.3,
            gust_kph: 8.5,
            uv: 1.0
          },
          {
            time_epoch: 1697522400,
            time: '2023-10-17 01:00',
            temp_c: 11.8,
            temp_f: 53.2,
            is_day: 0,
            condition: {
              text: Text.Clear,
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 345,
            wind_dir: 'NNW',
            pressure_mb: 1017.0,
            pressure_in: 30.04,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 74,
            cloud: 21,
            feelslike_c: 11.4,
            feelslike_f: 52.6,
            windchill_c: 11.4,
            windchill_f: 52.6,
            heatindex_c: 11.8,
            heatindex_f: 53.2,
            dewpoint_c: 7.4,
            dewpoint_f: 45.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 1.0
          },
          {
            time_epoch: 1697526000,
            time: '2023-10-17 02:00',
            temp_c: 11.3,
            temp_f: 52.3,
            is_day: 0,
            condition: {
              text: Text.Clear,
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 315,
            wind_dir: 'NW',
            pressure_mb: 1017.0,
            pressure_in: 30.04,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 77,
            cloud: 21,
            feelslike_c: 11.0,
            feelslike_f: 51.9,
            windchill_c: 11.0,
            windchill_f: 51.9,
            heatindex_c: 11.3,
            heatindex_f: 52.3,
            dewpoint_c: 7.4,
            dewpoint_f: 45.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.0,
            gust_kph: 6.4,
            uv: 1.0
          },
          {
            time_epoch: 1697529600,
            time: '2023-10-17 03:00',
            temp_c: 11.1,
            temp_f: 52.0,
            is_day: 0,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 307,
            wind_dir: 'NW',
            pressure_mb: 1017.0,
            pressure_in: 30.04,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 78,
            cloud: 33,
            feelslike_c: 10.9,
            feelslike_f: 51.6,
            windchill_c: 10.9,
            windchill_f: 51.6,
            heatindex_c: 11.1,
            heatindex_f: 52.0,
            dewpoint_c: 7.4,
            dewpoint_f: 45.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.4,
            gust_kph: 5.5,
            uv: 1.0
          },
          {
            time_epoch: 1697533200,
            time: '2023-10-17 04:00',
            temp_c: 11.5,
            temp_f: 52.7,
            is_day: 0,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 317,
            wind_dir: 'NW',
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 11.9,
            feelslike_f: 53.4,
            windchill_c: 11.9,
            windchill_f: 53.4,
            heatindex_c: 11.5,
            heatindex_f: 52.7,
            dewpoint_c: 9.1,
            dewpoint_f: 48.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.5,
            gust_kph: 5.7,
            uv: 1.0
          },
          {
            time_epoch: 1697536800,
            time: '2023-10-17 05:00',
            temp_c: 11.4,
            temp_f: 52.5,
            is_day: 0,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 337,
            wind_dir: 'NNW',
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 86,
            cloud: 100,
            feelslike_c: 11.4,
            feelslike_f: 52.5,
            windchill_c: 11.4,
            windchill_f: 52.5,
            heatindex_c: 11.4,
            heatindex_f: 52.5,
            dewpoint_c: 9.2,
            dewpoint_f: 48.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.2,
            gust_kph: 3.5,
            uv: 1.0
          },
          {
            time_epoch: 1697540400,
            time: '2023-10-17 06:00',
            temp_c: 11.4,
            temp_f: 52.5,
            is_day: 0,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009
            },
            wind_mph: 0.7,
            wind_kph: 1.1,
            wind_degree: 335,
            wind_dir: 'NNW',
            pressure_mb: 1020.0,
            pressure_in: 30.11,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 87,
            cloud: 100,
            feelslike_c: 11.9,
            feelslike_f: 53.5,
            windchill_c: 11.9,
            windchill_f: 53.5,
            heatindex_c: 11.4,
            heatindex_f: 52.5,
            dewpoint_c: 9.3,
            dewpoint_f: 48.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 1.3,
            gust_kph: 2.1,
            uv: 1.0
          },
          {
            time_epoch: 1697544000,
            time: '2023-10-17 07:00',
            temp_c: 11.4,
            temp_f: 52.5,
            is_day: 1,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 310,
            wind_dir: 'NW',
            pressure_mb: 1020.0,
            pressure_in: 30.12,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 87,
            cloud: 100,
            feelslike_c: 11.7,
            feelslike_f: 53.0,
            windchill_c: 11.7,
            windchill_f: 53.0,
            heatindex_c: 11.4,
            heatindex_f: 52.5,
            dewpoint_c: 9.4,
            dewpoint_f: 48.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.0,
            gust_kph: 4.9,
            uv: 3.0
          },
          {
            time_epoch: 1697547600,
            time: '2023-10-17 08:00',
            temp_c: 11.8,
            temp_f: 53.2,
            is_day: 1,
            condition: {
              text: Text.Cloudy,
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 311,
            wind_dir: 'NW',
            pressure_mb: 1020.0,
            pressure_in: 30.13,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 86,
            cloud: 64,
            feelslike_c: 11.9,
            feelslike_f: 53.4,
            windchill_c: 11.9,
            windchill_f: 53.4,
            heatindex_c: 11.8,
            heatindex_f: 53.2,
            dewpoint_c: 9.5,
            dewpoint_f: 49.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 1.7,
            gust_kph: 2.7,
            uv: 3.0
          },
          {
            time_epoch: 1697551200,
            time: '2023-10-17 09:00',
            temp_c: 12.8,
            temp_f: 55.0,
            is_day: 1,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003
            },
            wind_mph: 2.0,
            wind_kph: 3.2,
            wind_degree: 312,
            wind_dir: 'NW',
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 79,
            cloud: 51,
            feelslike_c: 12.8,
            feelslike_f: 55.1,
            windchill_c: 12.8,
            windchill_f: 55.1,
            heatindex_c: 12.8,
            heatindex_f: 55.0,
            dewpoint_c: 9.3,
            dewpoint_f: 48.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.3,
            gust_kph: 3.7,
            uv: 4.0
          },
          {
            time_epoch: 1697554800,
            time: '2023-10-17 10:00',
            temp_c: 14.1,
            temp_f: 57.4,
            is_day: 1,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 323,
            wind_dir: 'NW',
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 71,
            cloud: 59,
            feelslike_c: 14.2,
            feelslike_f: 57.6,
            windchill_c: 14.2,
            windchill_f: 57.6,
            heatindex_c: 14.1,
            heatindex_f: 57.4,
            dewpoint_c: 8.9,
            dewpoint_f: 48.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.1,
            gust_kph: 5.0,
            uv: 4.0
          },
          {
            time_epoch: 1697558400,
            time: '2023-10-17 11:00',
            temp_c: 15.2,
            temp_f: 59.4,
            is_day: 1,
            condition: {
              text: Text.Cloudy,
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 329,
            wind_dir: 'NNW',
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 77,
            feelslike_c: 15.2,
            feelslike_f: 59.4,
            windchill_c: 15.2,
            windchill_f: 59.4,
            heatindex_c: 15.2,
            heatindex_f: 59.4,
            dewpoint_c: 8.9,
            dewpoint_f: 48.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 4.0
          },
          {
            time_epoch: 1697562000,
            time: '2023-10-17 12:00',
            temp_c: 16.2,
            temp_f: 61.2,
            is_day: 1,
            condition: {
              text: Text.Cloudy,
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 326,
            wind_dir: 'NNW',
            pressure_mb: 1020.0,
            pressure_in: 30.12,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 82,
            feelslike_c: 16.2,
            feelslike_f: 61.2,
            windchill_c: 16.2,
            windchill_f: 61.2,
            heatindex_c: 16.2,
            heatindex_f: 61.2,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 4.0
          },
          {
            time_epoch: 1697565600,
            time: '2023-10-17 13:00',
            temp_c: 17.1,
            temp_f: 62.8,
            is_day: 1,
            condition: {
              text: Text.Cloudy,
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 310,
            wind_dir: 'NW',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 58,
            cloud: 76,
            feelslike_c: 17.1,
            feelslike_f: 62.8,
            windchill_c: 17.1,
            windchill_f: 62.8,
            heatindex_c: 17.1,
            heatindex_f: 62.8,
            dewpoint_c: 8.7,
            dewpoint_f: 47.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 4.0
          },
          {
            time_epoch: 1697569200,
            time: '2023-10-17 14:00',
            temp_c: 17.9,
            temp_f: 64.2,
            is_day: 1,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 309,
            wind_dir: 'NW',
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 55,
            cloud: 56,
            feelslike_c: 17.9,
            feelslike_f: 64.2,
            windchill_c: 17.9,
            windchill_f: 64.2,
            heatindex_c: 17.9,
            heatindex_f: 64.2,
            dewpoint_c: 8.9,
            dewpoint_f: 48.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 5.0
          },
          {
            time_epoch: 1697572800,
            time: '2023-10-17 15:00',
            temp_c: 14.4,
            temp_f: 57.9,
            is_day: 1,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 270,
            wind_dir: 'W',
            pressure_mb: 1020.0,
            pressure_in: 30.13,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 57,
            cloud: 100,
            feelslike_c: 18.2,
            feelslike_f: 64.8,
            windchill_c: 18.2,
            windchill_f: 64.8,
            heatindex_c: 18.2,
            heatindex_f: 64.8,
            dewpoint_c: 9.0,
            dewpoint_f: 48.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 16.0,
            vis_miles: 9.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 4.0
          },
          {
            time_epoch: 1697576400,
            time: '2023-10-17 16:00',
            temp_c: 18.2,
            temp_f: 64.8,
            is_day: 1,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 312,
            wind_dir: 'NW',
            pressure_mb: 1018.0,
            pressure_in: 30.06,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 56,
            cloud: 53,
            feelslike_c: 18.2,
            feelslike_f: 64.8,
            windchill_c: 18.2,
            windchill_f: 64.8,
            heatindex_c: 18.2,
            heatindex_f: 64.8,
            dewpoint_c: 9.2,
            dewpoint_f: 48.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 5.0
          },
          {
            time_epoch: 1697580000,
            time: '2023-10-17 17:00',
            temp_c: 17.8,
            temp_f: 64.0,
            is_day: 1,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003
            },
            wind_mph: 2.0,
            wind_kph: 3.2,
            wind_degree: 310,
            wind_dir: 'NW',
            pressure_mb: 1018.0,
            pressure_in: 30.06,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 58,
            cloud: 59,
            feelslike_c: 17.8,
            feelslike_f: 64.0,
            windchill_c: 17.8,
            windchill_f: 64.0,
            heatindex_c: 17.8,
            heatindex_f: 64.0,
            dewpoint_c: 9.5,
            dewpoint_f: 49.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.6,
            gust_kph: 4.2,
            uv: 5.0
          },
          {
            time_epoch: 1697583600,
            time: '2023-10-17 18:00',
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 1,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 52,
            wind_dir: 'NE',
            pressure_mb: 1018.0,
            pressure_in: 30.07,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 60,
            cloud: 59,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            windchill_c: 17.4,
            windchill_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            dewpoint_c: 9.7,
            dewpoint_f: 49.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.0,
            gust_kph: 4.8,
            uv: 5.0
          },
          {
            time_epoch: 1697587200,
            time: '2023-10-17 19:00',
            temp_c: 17.1,
            temp_f: 62.8,
            is_day: 0,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003
            },
            wind_mph: 2.5,
            wind_kph: 4.0,
            wind_degree: 81,
            wind_dir: 'E',
            pressure_mb: 1018.0,
            pressure_in: 30.07,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 62,
            cloud: 60,
            feelslike_c: 17.1,
            feelslike_f: 62.8,
            windchill_c: 17.1,
            windchill_f: 62.8,
            heatindex_c: 17.1,
            heatindex_f: 62.8,
            dewpoint_c: 9.8,
            dewpoint_f: 49.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 1.0
          },
          {
            time_epoch: 1697590800,
            time: '2023-10-17 20:00',
            temp_c: 16.1,
            temp_f: 61.0,
            is_day: 0,
            condition: {
              text: Text.Overcast,
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003
            },
            wind_mph: 2.5,
            wind_kph: 4.0,
            wind_degree: 101,
            wind_dir: 'ESE',
            pressure_mb: 1018.0,
            pressure_in: 30.07,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 58,
            feelslike_c: 16.1,
            feelslike_f: 61.0,
            windchill_c: 16.1,
            windchill_f: 61.0,
            heatindex_c: 16.1,
            heatindex_f: 61.0,
            dewpoint_c: 9.3,
            dewpoint_f: 48.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 1.0
          },
          {
            time_epoch: 1697594400,
            time: '2023-10-17 21:00',
            temp_c: 15.9,
            temp_f: 60.6,
            is_day: 0,
            condition: {
              text: Text.Cloudy,
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 122,
            wind_dir: 'ESE',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 64,
            feelslike_c: 15.9,
            feelslike_f: 60.6,
            windchill_c: 15.9,
            windchill_f: 60.6,
            heatindex_c: 15.9,
            heatindex_f: 60.6,
            dewpoint_c: 9.3,
            dewpoint_f: 48.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.6,
            gust_kph: 9.0,
            uv: 1.0
          },
          {
            time_epoch: 1697598000,
            time: '2023-10-17 22:00',
            temp_c: 15.7,
            temp_f: 60.3,
            is_day: 0,
            condition: {
              text: Text.Cloudy,
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 139,
            wind_dir: 'SE',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 71,
            feelslike_c: 15.7,
            feelslike_f: 60.3,
            windchill_c: 15.7,
            windchill_f: 60.3,
            heatindex_c: 15.7,
            heatindex_f: 60.3,
            dewpoint_c: 9.1,
            dewpoint_f: 48.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.6,
            gust_kph: 10.6,
            uv: 1.0
          },
          {
            time_epoch: 1697601600,
            time: '2023-10-17 23:00',
            temp_c: 15.5,
            temp_f: 59.9,
            is_day: 0,
            condition: {
              text: Text.Cloudy,
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 149,
            wind_dir: 'SSE',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 66,
            feelslike_c: 15.5,
            feelslike_f: 59.9,
            windchill_c: 15.5,
            windchill_f: 59.9,
            heatindex_c: 15.5,
            heatindex_f: 59.9,
            dewpoint_c: 9.0,
            dewpoint_f: 48.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.5,
            gust_kph: 12.1,
            uv: 1.0
          }
        ]
      }
    ]
  }
}
